### ISSUE TITLE
Add validation for the ticker

### ISSUE THREAD

**Issue by ghostbuster91** [chrispalaskas/cardano-skepsis-toolbox#5]
First time when I run the script it failed with the following error:
```
Generated certificate

Command failed: stake-pool metadata-hash  Error: Error validating stake pool metadata: Error in $: "ticker" must have at least 3 and at most 5 characters, but it has 6 characters.
```

The worst part was that it failed at the very end of the process. 
It would be much better to add some simple validation for the input data, especially for the ticker as it is not obvious that it has to be between 3 and 5.

**Comment by chrispalaskas** [comment]
Absolutely, makes sense. I'll fix that. Thanks!

**Comment by chrispalaskas** [comment]
I have added checks for Ticker validity and replaced some hard coded values with arguments:
[0c9a6331fc5d7676773b1e6d1b1fad081dd879d5](https://github.com/chrispalaskas/cardano-skepsis-toolbox/commit/0c9a6331fc5d7676773b1e6d1b1fad081dd879d5)
